// Parity tests: the TS ports of planner.py / shopping.py must reproduce the
// Python tools' output exactly. Fixtures are generated by scripts/gen_fixtures.py.
import { describe, it, expect } from "vitest";
import { recipes, recipesById } from "../recipes";
import { buildPlan, cookedMeals } from "../planner";
import { buildList, type ShoppingList } from "../shopping";

import planDefault from "../__fixtures__/plan_default.json";
import shoppingPlanDefault from "../__fixtures__/shopping_plan_default.json";
import shoppingFixed12 from "../__fixtures__/shopping_fixed12.json";
import fixed12Ids from "../__fixtures__/shopping_fixed12_ids.json";

// Convert our ordered-sections shape into the fixture's {Section: pairs} object.
function toFixtureShape(list: ShoppingList) {
  return {
    sections: Object.fromEntries(list.sections.map((s) => [s.section, s.items])),
    staples: list.staples,
  };
}

// Reduce a plan to the comparable subset the Python fixture stores.
function planToFixtureShape(plan: ReturnType<typeof buildPlan>) {
  return plan.map((d) => ({
    day: d.day,
    snack: d.snack,
    breakfast: d.breakfast,
    lunch: d.lunch,
    dinner: d.dinner,
  }));
}

describe("data bundle", () => {
  it("loads all 278 recipes in sorted-path order", () => {
    expect(recipes.length).toBe(278);
    const sorted = [...recipes].map((r) => r.id);
    // breakfast dir sorts before dinner/lunch/snack; first id is the antiguan one.
    expect(recipes[0].id).toBe("antiguan-breakfast-chop-up-and-saltfish");
    expect(new Set(sorted).size).toBe(278);
  });
});

describe("planner parity", () => {
  it("reproduces the Python default weekly plan exactly", () => {
    const plan = buildPlan(recipes); // defaults match planner.build_plan
    expect(planToFixtureShape(plan)).toEqual(planDefault.plan);
  });

  it("shopping list for the default plan's cooked meals matches Python", () => {
    const plan = buildPlan(recipes);
    const list = buildList(cookedMeals(plan, recipesById));
    expect(toFixtureShape(list)).toEqual(shoppingPlanDefault);
  });
});

describe("shopping parity (planner-independent)", () => {
  it("matches Python for a fixed set of 12 recipes", () => {
    const meals = fixed12Ids.ids.map((id) => recipesById.get(id)!);
    expect(meals.every(Boolean)).toBe(true);
    const list = buildList(meals);
    expect(toFixtureShape(list)).toEqual(shoppingFixed12);
  });
});
